# Spring properties
spring:
  application:
    name: kb-service  # Service registers under this name
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    metadataMap:
      instanceId: kbService1

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port